### PR TITLE
Add exported targets line to CMakeLists

### PR DESCRIPTION
**Pull request by bhomberg**
Without this, I get a build error that industrial_msgs/RobotStatus.h can't be found.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Interesting.

Both locally and on the ROS buildfarm I've never run into build issues.

I'll check.

**Comment by gavanderhoorn** [comment]
Could you provide a little more info on your build environment?

I've just built the pkgs in this repository from source on both Kinetic and Melodic with both `catkin_make` and `catkin_tools`, with both an `apt` installed `industrial_msgs` and a source checkout in the workspace and I've not been able to reproduce your build error.

This is on a 72 core machine, so significant parallelism during the build as well.

**Comment by bhomberg** [comment]
I'm running Ubuntu 18.04 (was building first on my non-PREEMPT-RT patched machine) and using melodic and catkin_make.  I have 12 cores and am building a bunch of other packages from source, including all of moveit.  I have industrial_core from source (as well as this package, of course).  I didn't see it the first time I checked it out (industrial_core already built) but I ran into it when I did a clean build.  

Let me know if there's any other information that would be helpful to you.

**Comment by gavanderhoorn** [comment]
>  I have industrial_core from source

off-topic, but: why? `industrial_core` and all its packages have been released into Melodic.

**Comment by bhomberg** [comment]
It looks like industrial_core hadn't been released for melodic when we switched to melodic -- we're actually building from the kinetic-devel branch.

**Comment by gavanderhoorn** [comment]
It's been released since 12 February, so no need for a source build any more.

**Comment by bhomberg** [comment]
Yep -- we'll definitely switch over the next time we have time to do some cleanup.

**Comment by gavanderhoorn** [comment]
Thanks for the fix @bhomberg :+1:

**Pull request merged**
